const orchids = [
  {
    id: '1',
    name: 'Statuesque Allure',
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/oc1704_1200px_revised.jpg?sfvrsn=0',
    color: 'pink',
    numberOfLike: 192,
    origin: 'Taiwan',
    category: 'Cattleya'
  },
  {
    id: '2',
    name: 'Marbled Charisma',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/Orchids/ps2303-marbled-charisma-mini-purple-orchids-1a.jpg?sfvrsn=2',
    color: 'white',
    numberOfLike: 90,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
  {
    id: '3',
    name: 'Violet Dream',
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/Orchids/oc2401-violet-dream-2-mini-light-purple-orchids-1a.jpg?sfvrsn=0',
    color: 'pink',
    numberOfLike: 234,
    origin: 'Taiwan',
    category: 'Cattleya'
  },
  {
    id: '4',
    name: 'Queen Joy',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/Orchids/oc2203_queen-joy_1a.jpg?sfvrsn=0',
    color: 'yellow',
    numberOfLike: 150,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
  {
    id: '5',
    name: 'Imperial Luxe',
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/Orchids/ps2304-imperial-luxe-mini-purple-orchids-1a.jpg?sfvrsn=2',
    color: 'pink',
    numberOfLike: 80,
    origin: 'Taiwan',
    category: 'Cattleya'
  },
  {
    id: '6',
    name: 'Cheerful Autumn',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/flowers/table-arrangements/ar1420_-cheerful-autumn.jpg?sfvrsn=0',
    color: 'white',
    numberOfLike: 150,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
  {
    id: '7',
    name: 'Elegant Epitome',
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/Orchids/oc1605-potted-orchids.jpg?sfvrsn=0',
    color: 'pink',
    numberOfLike: 192,
    origin: 'Taiwan',
    category: 'Cattleya'
  },
  {
    id: '8',
    name: 'Imperial Luxe',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/Orchids/ps2304-imperial-luxe-mini-purple-orchids-1a.jpg?sfvrsn=2',
    color: 'white',
    numberOfLike: 320,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
  {
    id: '9',
    name: 'Noble Lady',
    rating: 5,
    isSpecial: true,
    isNatural: false,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/Orchids/oc2202-noble-lady-2-light-purple-orchids-1a.jpg?sfvrsn=0',
    color: 'pink',
    Price: 245,
    origin: 'Taiwan',
    category: 'Cattleya'
  },
  {
    id: '10',
    name: 'Flourishing Elegance',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/Orchids/oc1801_1200_revised.jpg?sfvrsn=0',
    color: 'white',
    numberOfLike: 159,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
  {
    id: '11',
    name: 'Enlightened Aquarius',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/Astrology-Aquarius/zaq2020-enlightened-aquarius-astrology-flowers79b97fa9350a62b6a920ff0000e4902b.jpg?sfvrsn=0',
    color: 'white',
    numberOfLike: 150,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
  {
    id: '12',
    name: 'Splash of the tropics',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/flowers/oc1802-splash-of-the-tropics.jpg?sfvrsn=0',
    color: 'white',
    numberOfLike: 150,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
  {
    id: '13',
    name: 'Statuesque Allure',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/oc1704_1200px_revised.jpg?sfvrsn=0',
    color: 'white',
    numberOfLike: 150,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
  {
    id: '14',
    name: 'My Everything',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/collections/Cup-Of-Blooms/ks1524-monogram-cup-arrangement.jpg?sfvrsn=0',
    color: 'white',
    numberOfLike: 190,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
  {
    id: '15',
    name: 'Intertwining Fate',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/collections/Cup-Of-Blooms/ks1906-intertwining-fate231053a9350a62b6a920ff0000e4902b.jpg?sfvrsn=0',
    color: 'white',
    numberOfLike: 150,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
  {
    id: '16',
    name: 'Moon Orchid',
    rating: 4,
    isSpecial: false,
    isNatural: true,
    image: 'https://www.xpressflower.com/images/default-source/plants-and-gifts/Orchids/ps2304-imperial-luxe-mini-purple-orchids-1a.jpg?sfvrsn=2',
    color: 'white',
    numberOfLike: 70,
    origin: 'Indonesia',
    category: 'Phalaenopsis'
  },
    
];

export default orchids;
